### PR TITLE
Add fw page

### PR DESCRIPTION
**Pull request by saparikh**
A dedicated page for firewall analysis.

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish.github.io/90)* status: all files reviewed, 7 unresolved discussions (waiting on @saparikh)

___
*[_pages/firewall_analysis.html, line 12 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-Mcjhula-astfJYUeO2-:-Mcjhula-astfJYUeO20:b8jvh3a) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L12)):*
> ```HTML
>   <div class="post-content">
> 
> Manually reasoning about what an ACL or firewall policy will do to a packet, when it has rules that cover multiple fields of the IP header is extremely difficult, and as the rules grow in size becomes virtually impossible. Add to that the task of understanding what a change to the ACL or firewall policy will do, and you are in for quite a ride.
> ```

comma after "IP header".  

start a new sentence after "difficult". if not, comma after "size".
___
*[_pages/firewall_analysis.html, line 14 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-McjiHfo1uCIQrHQIKq1:-McjiHfp4sibJ5P4rOlM:bhcgeem) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L14)):*
> ```HTML
> Manually reasoning about what an ACL or firewall policy will do to a packet, when it has rules that cover multiple fields of the IP header is extremely difficult, and as the rules grow in size becomes virtually impossible. Add to that the task of understanding what a change to the ACL or firewall policy will do, and you are in for quite a ride.
> 
> But this is where a tool such as Batfish comes into play. It provides multiple methods of analyzing ACLs and firewall rules, so that you can ensure that your security policy functions as desired. And it is built for you to do this programmatically, so you can easily incorporate this into any workflow.
> ```

Remove leading "But" 
___
*[_pages/firewall_analysis.html, line 31 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-Mcjj-n07e1yv4-yUaxX:-Mcjj-n07e1yv4-yUaxY:butg68k) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L31)):*
> ```HTML
> 
> 
> The <span style="font-family: monospace, monospace; font-weight: 600;"><b>testFilters</b></span> query allows you to analyze the behavior of a filter with respect to a specific flow. For example, if I want to determine if an ACL is allowing a specific host to reach the DNS server, I would use <span style="font-family: monospace, monospace; font-weight: 600;"><b>testFilters</b></span> as shown below.
> ```

the term "filter" appears out of the blue. mention someplace what it means.
___
*[_pages/firewall_analysis.html, line 45 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-McjjNIF3twfKiIrJ2b7:-McjjNIG92bwzy4gDalF:b46upj0) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L45)):*
> ```HTML
>                     filters="acl_in").answer()
>     <p><br></p>
> show(answer.frame())
> ```

this "show" command won't work unless someone imports the startup.py file from the notebooks folder. if you are expecting users to be able to cut-n-paste this code, remove this line and and remove "answer =" from the previous line. 
___
*[_pages/firewall_analysis.html, line 168 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-McjkJnj6lF30JJaKh1w:-McjkJnj6lF30JJaKh1x:b-2seyz0) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L168)):*
> ```HTML
> 
> What once started out as a nice pristine and easy to understand ACL or firewall policy, over time turns into quite a
>       mess as the network and services evolve. Oftentimes you end up creating new rules that are partially or fully
> ```

comma after "Oftentimes"
___
*[_pages/firewall_analysis.html, line 180 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-Mcjka6D0oAqAeihBiR7:-Mcjka6D0oAqAeihBiR8:b-a6btjw) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L180)):*
> ```HTML
> aclAns = bfq.filterLineReachability(nodes="rtr-with-acl").answer()
> <p><br></p>
> show(aclAns.frame().sort_values(by="Unreachable_Line"))
> ```

is this pandas magic necessary here? you can have the same output below without sorting since this content is all a bit abstract anyway.
___
*[_pages/firewall_analysis.html, line 252 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-McjlADyCbmYMthevoaT:-McjlADyCbmYMthevoaU:bwbf655) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L252)):*
> ```HTML
> <i># Initialize a snapshot with the original ACL</i>
> <p>
> <i>original_snapshot </i> bf_session.init_snapshot_from_text(
> ```

init_snapshot_from_text seems to be introducing an unnecessary diversion. might leave people with the impression that it is how you use compare filters and cannot just feed in config files. since we are not showing the acls themselves, cut this out and simply show the query (with some information about snapshot and reference_snapshot).

**Comment by saparikh** [comment]
___
*[_pages/firewall_analysis.html, line 12 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-Mcjhula-astfJYUeO2-:-McupU4YETkd-VKRg1Sy:bb7f2mf) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L12)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

comma after "IP header".  

start a new sentence after "difficult". if not, comma after "size".

</blockquote></details>

done

**Comment by saparikh** [comment]
___
*[_pages/firewall_analysis.html, line 45 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-McjjNIF3twfKiIrJ2b7:-McuptihClpsKnvhx8YT:bonw87i) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L45)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

this "show" command won't work unless someone imports the startup.py file from the notebooks folder. if you are expecting users to be able to cut-n-paste this code, remove this line and and remove "answer =" from the previous line. 
</blockquote></details>

not expecting them to cut-n-paste this code. the notebooks links are there for that reason.

**Comment by saparikh** [comment]
___
*[_pages/firewall_analysis.html, line 180 at r3](https://reviewable.io/reviews/batfish/batfish.github.io/90#-Mcjka6D0oAqAeihBiR7:-Mcuq5OgEJjrrR4mXEZg:b-gyyr4t) ([raw file](https://github.com/batfish/batfish.github.io/blob/ff735635609257269a63849439ec4d39b0c7fb53/_pages/firewall_analysis.html#L180)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

is this pandas magic necessary here? you can have the same output below without sorting since this content is all a bit abstract anyway.
</blockquote></details>

I copied it from the notebook as is. Deleting it won't matter though.

**Comment by saparikh** [comment]
Addressed comments from @ratulm with latest commit

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish.github.io/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @saparikh)

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/batfish.github.io/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @saparikh)

**Pull request merged**
