### PR TITLE
Add javadocs at /docs/index.html

### PR DESCRIPTION
**Pull request by corinaminer**

### CODE REVIEW

**Comment by vasu018** [comment]
___
*[docs/options, line 7 at r1](https://reviewable.io/reviews/batfish/batfish.github.io/13#-LIIihuI4eS3rrVGr4xD:-LIIihuJD6V6KixtBRll:bfdcs8s) ([raw file](https://github.com/batfish/batfish.github.io/blob/d7106e06e1b3c7991cd5293a2f3e9117a70d3382/docs/options#L7)):*
> ```
> -protected
> -quiet
> -sourcepath
> ```

Is this acceptable to have hardcoded value in the options file. which is used for generating the docs. Should we set it and refer it from the $PATH or so?

**Comment by vasu018** [comment]
___
*[docs/options, line 7 at r1](https://reviewable.io/reviews/batfish/batfish.github.io/13#-LIIihuI4eS3rrVGr4xD:-LIIj8PtDm9MAZD0DWml:b-ys5r4i) ([raw file](https://github.com/batfish/batfish.github.io/blob/d7106e06e1b3c7991cd5293a2f3e9117a70d3382/docs/options#L7)):*
<details><summary><i>Previously, vasu018 (Vasudevan Nagendra) wrote…</i></summary><blockquote>

Is this acceptable to have hardcoded value in the options file. which is used for generating the docs. Should we set it and refer it from the $PATH or so?
</blockquote></details>

Same for the other paths in this file.

**Comment by haverma** [comment]
Are the docs being generated for `batfish` project only ? I was not able to find docs for batfish-common-protocol or batfish-client or coordinator, may be github is not showing them, I am not sure

**Comment by vasu018** [comment]
:lgtm:

**Pull request merged**
